Repository kubernetes/node-problem-detector, pull requests merged in 2018-11, with the labels that each got.

#213 update the deployment file and use configmap
  README.md
  deployment/node-problem-detector-config.yaml
  deployment/node-problem-detector.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#217 Adding helm chart info to readme and fixing some formatting
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#221 Detect readonly filesystem
  config/kernel-monitor.json
  deployment/node-problem-detector-config.yaml
  test/kernel_log_generator/problems/readonly_filesystem
Labels: approved, cncf-cla: yes, lgtm, size/M

#219 fix broken link for draino
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#225 Fix typos: NDDE -> NODE, permenantly -> permanently
  cmd/options/options_test.go
  pkg/logcounter/log_counter_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#223 Detect kubelet and container runtime frequent restarts
  Makefile
  README.md
  cmd/logcounter/log_counter.go
  cmd/logcounter/options/options.go
  config/docker-monitor.json
  config/kernel-monitor-counter.json
  config/systemd-monitor-counter.json
  deployment/node-problem-detector-config.yaml
  pkg/custompluginmonitor/types/config.go
  pkg/logcounter/log_counter.go
  pkg/systemlogmonitor/logwatchers/filelog/log_watcher.go
  pkg/systemlogmonitor/logwatchers/filelog/log_watcher_test.go
  pkg/systemlogmonitor/logwatchers/journald/log_watcher.go
  pkg/systemlogmonitor/logwatchers/kmsg/log_watcher.go
  pkg/systemlogmonitor/logwatchers/kmsg/log_watcher_test.go
  pkg/systemlogmonitor/logwatchers/types/log_watcher.go
  pkg/util/helpers.go
  pkg/util/helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#224 Detect corrupt docker overlay2
  config/docker-monitor-counter.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#203 fix custom plugin monitor condition change
  pkg/custompluginmonitor/custom_plugin_monitor.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#228 More fix to custom plugin monitor condition change
  pkg/custompluginmonitor/custom_plugin_monitor.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#229 Add wangzhen127 as a maintainer.
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#231 Update base image for CVE fix.
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#233 Explicitly include libsystemd0 in the image.
  Dockerfile.in
Labels: approved, cncf-cla: yes, lgtm, size/XS
