Repository kubernetes/node-problem-detector, pull requests merged in 2018-05, with the labels that each got.

#164 Update Readme
  README.md
  deployment/node-problem-detector-old.yaml
  deployment/node-problem-detector.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#176 add SECURITY_CONTACTS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S

#177 fix typo in daemonset labelSelector
  deployment/node-problem-detector.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
