Repository kubernetes/node-problem-detector, pull requests merged in 2018-06, with the labels that each got.

#144 add setup readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#180 Add log-counter plugin written in go
  Makefile
  cmd/logcounter/log_counter.go
  cmd/logcounter/options/options.go
  config/kernel-monitor-counter.json
  pkg/custompluginmonitor/plugin/plugin.go
  pkg/custompluginmonitor/types/types.go
  pkg/logcounter/log_counter.go
  pkg/logcounter/log_counter_test.go
  pkg/logcounter/types/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#182 Typo fix: encounts->encounters
  pkg/systemlogmonitor/logwatchers/log_watchers.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#151 Improve cpm
  pkg/condition/manager_test.go
  pkg/custompluginmonitor/custom_plugin_monitor.go
  pkg/systemlogmonitor/log_monitor.go
  pkg/systemlogmonitor/log_monitor_test.go
  pkg/types/types.go
  pkg/util/convert.go
  pkg/util/convert_test.go
  pkg/util/helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#183 adjust client-go User-Agent
  pkg/problemclient/problem_client.go
  pkg/version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
