Repository kubernetes/node-problem-detector, pull requests merged in 2018-12, with the labels that each got.

#239 add docs about custom plugin
  README.md
  docs/custom_plugin_monitor.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#238 enable codnition updaet when message change for custom plugin
  config/custom-plugin-monitor.json
  docs/custom_plugin_monitor.md
  pkg/custompluginmonitor/custom_plugin_monitor.go
  pkg/custompluginmonitor/types/config.go
  pkg/custompluginmonitor/types/config_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#246 Add log-counter to the Dockerfile
  Dockerfile.in
Labels: approved, cncf-cla: yes, lgtm, size/XS

#245 add resource
  deployment/node-problem-detector.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
