Repository kubernetes/node-problem-detector, pull requests merged in 2019-11, with the labels that each got.

#381 Add xueweiz as maintainer.
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#379 add a case is ID="centos"
  pkg/util/helpers.go
  pkg/util/helpers_test.go
  pkg/util/testdata/os-release-centos
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#382 typo: delete redundant description.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#391 Trim go.mod
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#390 Fix build tags manipulation in Makefile
  .travis.yml
  Dockerfile.in
  Makefile
  cmd/logcounter/log_counter.go
  pkg/logcounter/log_counter.go
  pkg/logcounter/log_counter_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#370 Update node-problem-detector-config
  deployment/node-problem-detector-config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#369 Support "nf_conntrack", check for 90% full
  config/plugin/network_problem.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#392 Improve systemctl check, style + cleanup
  config/plugin/check_ntp.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#393 fix make test early failure
  test/e2e/metriconly/e2e_npd_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
