Repository kubernetes/node-problem-detector, pull requests merged in 2019-12, with the labels that each got.

#394 fix: modify typo
  pkg/exporters/stackdriver/config/config_test.go
  pkg/systemlogmonitor/logwatchers/filelog/log_watcher.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#395 Using time.Since(t) instead of t.Sub(time.Now())
  pkg/custompluginmonitor/plugin/plugin.go
  pkg/exporters/k8sexporter/condition/manager.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#400 Install ginkgo executable in test/build.sh
  test/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#402 Ignore first collected disk stats to prevent metric distortion
  pkg/systemstatsmonitor/disk_collector.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
