Repository kubernetes/node-problem-detector, pull requests merged in 2019-03, with the labels that each got.

#257 Fix travis ci file
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#260 Update embargo doc link in SECURITY_CONTACTS and change PST to PSC
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#254 Add script for presubmit and CI jobs
  .gitignore
  test/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#261 Install system lib in build.sh
  test/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#262 Fix CI job race condition
  test/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#263 Register gcloud as a Docker credential in Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS
