Repository kubernetes/node-problem-detector, pull requests merged in 2019-10, with the labels that each got.

#371 Update README
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#373 Decrease default frequency of forced heartbeats to 5m
  cmd/options/options.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#367 untangle plugin runner a bit
  pkg/custompluginmonitor/plugin/plugin.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#359 fix close of closed channel
  pkg/custompluginmonitor/custom_plugin_monitor.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#339 avoid log channel closed caused endless loop
  pkg/systemlogmonitor/log_monitor.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#375 Properly close channel when monitors exit.
  cmd/logcounter/log_counter.go
  pkg/custompluginmonitor/custom_plugin_monitor.go
  pkg/custompluginmonitor/plugin/plugin.go
  pkg/logcounter/log_counter.go
  pkg/logcounter/log_counter_test.go
  pkg/logcounter/types/types.go
  pkg/systemlogmonitor/log_monitor.go
  pkg/systemlogmonitor/logwatchers/kmsg/log_watcher.go
  test/e2e/lib/gce/instance.go
Labels: approved, cncf-cla: yes, lgtm, size/M
