Repository kubernetes/node-problem-detector, pull requests merged in 2019-06, with the labels that each got.

#283 Update README to state that the ConfigMap is required.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#285 Add metrics mode proposal to README
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#288 Run custom plugins immediately on startup
  pkg/custompluginmonitor/plugin/plugin.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#290 Remove TestGoroutineLeak unit tests.
  pkg/systemlogmonitor/log_monitor_test.go
  pkg/systemlogmonitor/logwatchers/filelog/log_watcher_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#275 node-problem-detector: report disk queue length in Prometheus format
  README.md
  cmd/node_problem_detector.go
  cmd/options/options.go
  cmd/options/options_test.go
  cmd/plugins.go
  config/system-stats-monitor.json
  pkg/custompluginmonitor/custom_plugin_monitor.go
  pkg/custompluginmonitor/custom_plugin_monitor_test.go
  pkg/custompluginmonitor/types/config_test.go
  pkg/exporters/k8sexporter/condition/manager.go
  pkg/exporters/k8sexporter/condition/manager_test.go
  pkg/exporters/k8sexporter/k8s_exporter.go
  pkg/exporters/k8sexporter/problemclient/fake_problem_client.go
  pkg/exporters/k8sexporter/problemclient/problem_client.go
  pkg/exporters/k8sexporter/problemclient/problem_client_test.go
  pkg/exporters/prometheusexporter/prometheus_exporter.go
  pkg/problemdaemon/problem_daemon.go
  pkg/problemdaemon/problem_daemon_test.go
  pkg/problemdetector/problem_detector.go
  pkg/systemlogmonitor/log_monitor.go
  pkg/systemlogmonitor/log_monitor_test.go
  pkg/systemstatsmonitor/README.md
  pkg/systemstatsmonitor/disk_collector.go
  pkg/systemstatsmonitor/metric_helper.go
  pkg/systemstatsmonitor/system_stats_monitor.go
  pkg/systemstatsmonitor/system_stats_monitor_test.go
  pkg/systemstatsmonitor/types/config.go
  pkg/systemstatsmonitor/types/config_test.go
  pkg/types/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#293 Do not import plugins unnecessarily.
  Makefile
  cmd/node-problem-detector/node_problem_detector.go
  cmd/node-problem-detector/plugins.go
  cmd/options/options.go
  cmd/options/options_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#294 Allow compilation time disabling for each type of Problem Daemon.
  .travis.yml
  Makefile
  README.md
  cmd/nodeproblemdetector/node_problem_detector.go
  cmd/nodeproblemdetector/problemdaemonplugins/custom_plugin_monitor_plugin.go
  cmd/nodeproblemdetector/problemdaemonplugins/system_log_monitor_plugin.go
  cmd/nodeproblemdetector/problemdaemonplugins/system_stats_monitor_plugin.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#292 Add systemd monitor for kubelet, docker, and containerd restart events
  config/systemd-monitor.json
  test/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#299 Correctly identify failures in problem daemon starting.
  cmd/nodeproblemdetector/node_problem_detector.go
  pkg/problemdetector/problem_detector.go
  pkg/types/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
