Repository kubernetes/node-problem-detector, pull requests merged in 2019-08, with the labels that each got.

#319 Make systemd monitor look back for 5m
  config/systemd-monitor.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#318 Print monitor config path in the logs
  pkg/custompluginmonitor/custom_plugin_monitor.go
  pkg/systemlogmonitor/log_monitor.go
  pkg/systemstatsmonitor/system_stats_monitor.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#321 Update the detection method for docker overlay2 issue
  config/docker-monitor.json
  test/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#322 Bump base image debian-base to tag v1.0.0 to pick up some CVE fixes
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#320 Don't update condition if status stays False/Unknown for custom plugin
  pkg/custompluginmonitor/custom_plugin_monitor.go
  pkg/custompluginmonitor/types/config.go
  pkg/custompluginmonitor/types/config_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#325 fix a spelling error
  pkg/exporters/k8sexporter/problemclient/problem_client.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#327 Cherry pick #321 to v0.6: Update the detection method for docker overlay2 issue
  config/docker-monitor.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#328 Cherry pick 2f5d032 to v0.6: Don't update condition if status stays False/Unknown for custom plugin
  pkg/custompluginmonitor/custom_plugin_monitor.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#331 Move NPD into kube-system namespace
  deployment/node-problem-detector-config.yaml
  deployment/node-problem-detector-old.yaml
  deployment/node-problem-detector.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#334 Metric format fixes on host/uptime and disk/*
  pkg/systemstatsmonitor/disk_collector.go
  pkg/systemstatsmonitor/host_collector.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
