Repository kubernetes/node-problem-detector, pull requests merged in 2019-09, with the labels that each got.

#342 Fixes typo in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#350 fix a spelling error
  test/e2e/lib/gce/instance.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#341 Update network_problem.sh
  config/plugin/network_problem.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#353 Allow e2e test to pick up test VM image using image family
  Makefile
  test/e2e/metriconly/e2e_npd_test.go
  test/e2e/metriconly/metrics_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#352 Set SSH timeout to 5 minutes
  test/e2e/lib/gce/instance.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#356 Make heartbeatPeriod const into a flag
  cmd/options/options.go
  pkg/exporters/k8sexporter/condition/manager.go
  pkg/exporters/k8sexporter/condition/manager_test.go
  pkg/exporters/k8sexporter/k8s_exporter.go
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/S

#368 Add stackdriver exporter endpoint for problem_gauge
  pkg/exporters/stackdriver/stackdriver_exporter.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#363 remove kubernetes 1.8 support
  README.md
  deployment/node-problem-detector-old.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
