Repository kubernetes/node-problem-detector, pull requests merged in 2020-08, with the labels that each got.

#450 Fix typo in custom-plugin-monitor
  pkg/custompluginmonitor/custom_plugin_monitor.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#452 Add more info to disk metrics
  pkg/systemstatsmonitor/README.md
  pkg/systemstatsmonitor/disk_collector.go
  pkg/systemstatsmonitor/labels.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#453 Detect docker startup failures
  config/docker-monitor.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#458 Log custom plugin stderr only if the status is not ok.
  pkg/custompluginmonitor/plugin/plugin.go
  pkg/healthchecker/health_checker.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#459 Add logging levels to custom plugin logs.
  pkg/custompluginmonitor/custom_plugin_monitor.go
  pkg/custompluginmonitor/plugin/plugin.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
