Repository kubernetes/node-problem-detector, pull requests merged in 2020-11, with the labels that each got.

#484 Collect CPU load averages in a separate metric
  config/system-stats-monitor.json
  pkg/exporters/stackdriver/stackdriver_exporter.go
  pkg/systemstatsmonitor/README.md
  pkg/systemstatsmonitor/cpu_collector.go
  pkg/util/metrics/metric.go
  test/e2e/metriconly/metrics_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#430 avoid npd pod schedule on windows node
  deployment/node-problem-detector.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#478 fix: node memory metrics are off by 1024
  pkg/systemstatsmonitor/memory_collector.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#481 Adapt OOMKilling pattern to old and new Linux kernels
  config/kernel-monitor-filelog.json
  config/kernel-monitor.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#485 fix helm instructions
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#488 Add Detectection logic for I/O errors
  config/kernel-monitor.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#489 Kubelet api server connection check in health checker
  cmd/healthchecker/health_checker.go
  pkg/healthchecker/health_checker.go
  pkg/healthchecker/health_checker_test.go
  pkg/healthchecker/types/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#425 Grammar
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#497 avoid duplicating the disk bytes used metrics based on fstype and mount types
  pkg/systemstatsmonitor/disk_collector.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#475 catching hung task with pattern like "tasks airflow scheduler: *"
  config/kernel-monitor.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#500 Change default staging bucket.
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#455 fix: print result's message when status unknown
  pkg/custompluginmonitor/custom_plugin_monitor.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
