Repository kubernetes/node-problem-detector, pull requests merged in 2021-07, with the labels that each got.

#599 Fix NPD hash for test.
  test/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#575 Check kube-proxy health on linux
  pkg/healthchecker/health_checker.go
  pkg/healthchecker/health_checker_linux.go
  pkg/healthchecker/health_checker_test.go
  pkg/healthchecker/health_checker_windows.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#595 Add coverage.out to Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/windows, size/XS
