Repository kubernetes/node-problem-detector, pull requests merged in 2021-05, with the labels that each got.

#550 Detect when container process fails to start
  config/windows-containerd-monitor-filelog.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#547 Update node-problem-detector.yaml
  deployment/node-problem-detector.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#551 add tolerations in daemonset config file
  deployment/node-problem-detector.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#552 Add healthChecker functionality for kube-proxy service
  cmd/healthchecker/options/options.go
  config/windows-health-checker-kubeproxy.json
  pkg/healthchecker/health_checker_windows.go
  pkg/healthchecker/types/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#554 Add support for basic system metrics for Windows.
  README.md
  config/windows-system-stats-monitor.json
  pkg/systemstatsmonitor/README.md
  pkg/systemstatsmonitor/cpu_collector.go
  pkg/systemstatsmonitor/cpu_collector_linux.go
  pkg/systemstatsmonitor/cpu_collector_test.go
  pkg/systemstatsmonitor/cpu_collector_windows.go
  pkg/systemstatsmonitor/disk_collector_test.go
  pkg/systemstatsmonitor/host_collector_test.go
  pkg/systemstatsmonitor/memory_collector.go
  pkg/systemstatsmonitor/memory_collector_linux.go
  pkg/systemstatsmonitor/memory_collector_test.go
  pkg/systemstatsmonitor/memory_collector_windows.go
  pkg/util/exec_test.go
  pkg/util/helpers.go
  pkg/util/helpers_linux.go
  pkg/util/helpers_linux_test.go
  pkg/util/helpers_test.go
  pkg/util/helpers_windows.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#555 Add windows defender problem detection custom plugin
  config/plugin/windows_defender_problem.ps1
  config/windows-defender-monitor.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/node, sig/windows, size/M

#557 Make sure the path to known-modules.json is relative
  config/system-stats-monitor.json
  pkg/systemstatsmonitor/README.md
  pkg/systemstatsmonitor/system_stats_monitor.go
  pkg/systemstatsmonitor/system_stats_monitor_test.go
  pkg/systemstatsmonitor/types/config.go
  pkg/systemstatsmonitor/types/config_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#558 Fix the uptime timestamp parsing.
  pkg/healthchecker/types/types_linux.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#567 config/windows-defender-monitor.json
  config/windows-defender-monitor.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, priority/important-soon, sig/windows, size/XS

#561 Added arm64 targets for linux binaries
  .travis.yml
  Makefile
  README.md
  test/build.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, priority/important-soon, sig/node, size/M
