Repository kubernetes/node-problem-detector, pull requests merged in 2021-02, with the labels that each got.

#521 fix check for timeout
  pkg/custompluginmonitor/plugin/plugin.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#516 add metric for per-cpu, per-stage timing
  config/system-stats-monitor.json
  pkg/exporters/stackdriver/stackdriver_exporter.go
  pkg/systemstatsmonitor/README.md
  pkg/systemstatsmonitor/cpu_collector.go
  pkg/systemstatsmonitor/labels.go
  pkg/util/metrics/metric.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#526 Update CHANGELOG for past releases
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#527 Update image path in deployment yaml
  deployment/node-problem-detector.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#528 Add notes on steps to perform when doing a release
  docs/release_process.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#522 Remove os_version and kernel_version labels
  pkg/systemstatsmonitor/cpu_collector.go
  pkg/systemstatsmonitor/labels.go
  pkg/systemstatsmonitor/net_collector.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#529 Allow building on macOS
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#536 Make log pattern check configurable in health checker
  cmd/healthchecker/options/options.go
  pkg/healthchecker/health_checker.go
  pkg/healthchecker/types/types.go
  pkg/healthchecker/types/types_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#534 Add instructions for developing NPD on Windows
  README.md
Labels: approved, cncf-cla: yes, lgtm, sig/windows, size/M

#530 add memory read error
  config/kernel-monitor.json
  deployment/node-problem-detector-config.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#538 Fix for flaky unit test in health checker
  pkg/healthchecker/types/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
