Repository kubernetes/node-problem-detector, pull requests merged in 2021-01, with the labels that each got.

#511 Update list of supported problem daemons
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#510 Use Fatal instead of panic for go tests.
  test/e2e/metriconly/e2e_npd_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#501 Remove Dockerfile.in rewrite hack and use updated arg in Dockerfile
  .gitignore
  Dockerfile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#505 added a new metric to retrieve os features like unknown modules, KTD
  config/guestosconfig/known-modules.json
  config/system-stats-monitor.json
  pkg/exporters/stackdriver/stackdriver_exporter.go
  pkg/systemstatsmonitor/README.md
  pkg/systemstatsmonitor/labels.go
  pkg/systemstatsmonitor/osfeature_collector.go
  pkg/systemstatsmonitor/system_stats_monitor.go
  pkg/systemstatsmonitor/types/config.go
  pkg/systemstatsmonitor/types/config_test.go
  pkg/util/metrics/metric.go
  pkg/util/metrics/system/common.go
  test/e2e/metriconly/metrics_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#515 cleanup the log
  pkg/systemstatsmonitor/system_stats_monitor.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#509 Support filelog watching in Windows.
  Makefile
  config/windows-containerd-monitor-filelog.json
  go.mod
  pkg/systemlogmonitor/logwatchers/filelog/log_watcher_windows.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/M

#513 add metrics for process stats
  config/system-stats-monitor.json
  pkg/exporters/stackdriver/stackdriver_exporter.go
  pkg/systemstatsmonitor/README.md
  pkg/systemstatsmonitor/cpu_collector.go
  pkg/systemstatsmonitor/labels.go
  pkg/systemstatsmonitor/osfeature_collector.go
  pkg/util/metrics/metric.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#456 fix: fix script timeout can't work
  pkg/custompluginmonitor/plugin/plugin.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#512 Add network interface stats
  config/net-cgroup-system-stats-monitor.json
  config/systemd/node-problem-detector-metric-only.service
  pkg/exporters/stackdriver/stackdriver_exporter.go
  pkg/systemstatsmonitor/README.md
  pkg/systemstatsmonitor/labels.go
  pkg/systemstatsmonitor/net_collector.go
  pkg/systemstatsmonitor/system_stats_monitor.go
  pkg/systemstatsmonitor/types/config.go
  pkg/util/metrics/metric.go
  test/e2e-install.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#518 Add containerd health checker config.
  config/health-checker-containerd.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#519 Fix system-stats-monitor config indention.
  config/system-stats-monitor.json
Labels: approved, cncf-cla: yes, lgtm, size/M
