Repository kubernetes/node-problem-detector, pull requests merged in 2021-08, with the labels that each got.

#601 Add vteratipally as a reviewer
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#602 update make clean to remove coverage.out
  .gitignore
  Makefile
Labels: lgtm, cncf-cla: yes, size/XS, priority/important-soon, approved, sig/node, sig/windows, ok-to-test

#611 Fixed dead link
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#609 Prevent uptimeFunc from being called everytime CheckHealth is called
  pkg/healthchecker/health_checker.go
Labels: lgtm, cncf-cla: yes, size/M, priority/important-soon, approved, sig/node, sig/windows, ok-to-test

#612 Update powershell command for uptime to help efficiency
  pkg/healthchecker/health_checker_windows.go
Labels: lgtm, cncf-cla: yes, size/S, priority/important-soon, approved, sig/node, sig/windows, ok-to-test

#607 Create cloudbuild file
  cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#589 Update the instructions for build image in the readme
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#587 Add a check if the metric is nil so that collector doesn't collect metrics.
  pkg/systemstatsmonitor/cpu_collector_linux.go
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test
