Repository kubernetes/node-problem-detector, pull requests merged in 2021-06, with the labels that each got.

#574 Update windows command in README to allow windows to be build alone locally
  README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#580 update CriCtl path for windows
  pkg/healthchecker/types/types_windows.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/windows, size/XS

#585 Add HCS empty layer error reporting.
  config/windows-containerd-monitor-filelog.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#539 improvement health-checker
  cmd/healthchecker/options/options.go
  config/health-checker-kubelet.json
  deployment/node-problem-detector-healthchecker.yaml
  pkg/healthchecker/health_checker.go
  pkg/healthchecker/types/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#577 Bump image version from v1.0.0 to v.2.0.0 to fix some of the CVEs.
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#578 Reduce the number of reads to /proc/partitions file and gofmt.
  pkg/systemstatsmonitor/disk_collector.go
  pkg/systemstatsmonitor/system_stats_monitor_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#583 Log error from kube-api
  pkg/exporters/k8sexporter/k8s_exporter.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#570 Fix e2e-test flakes for Ext4 counter
  test/e2e/metriconly/metrics_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
