Repository kubernetes/node-problem-detector, pull requests merged in 2022-07, with the labels that each got.

#685 Remove unused resultChan field in CPM
  pkg/custompluginmonitor/custom_plugin_monitor.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#684 Create multi-arch image
  Dockerfile
  Makefile
  builder/Dockerfile
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#644 Create multi-arch image
  Dockerfile
  Makefile
  builder/Dockerfile
Labels: cncf-cla: yes, size/M, ok-to-test

#646 Allow skipping condition during customplugin initialization
  docs/custom_plugin_monitor.md
  pkg/custompluginmonitor/custom_plugin_monitor.go
  pkg/custompluginmonitor/types/config.go
  pkg/custompluginmonitor/types/config_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved, lifecycle/stale

#668 show failed statuses as warning
  pkg/custompluginmonitor/plugin/plugin.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#660 simplify cri health check
  pkg/healthchecker/health_checker.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#687 Updated the docs under NPD
  CONTRIBUTING.md
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#689 fix README under systemlogmonitor
  pkg/systemlogmonitor/README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test
