Repository kubernetes/node-problem-detector, pull requests merged in 2022-04, with the labels that each got.

#594 optimize netcollector implementation and custom `/proc` mount path
  pkg/systemstatsmonitor/cpu_collector.go
  pkg/systemstatsmonitor/cpu_collector_linux.go
  pkg/systemstatsmonitor/cpu_collector_test.go
  pkg/systemstatsmonitor/net_collector.go
  pkg/systemstatsmonitor/osfeature_collector.go
  pkg/systemstatsmonitor/system_stats_monitor.go
  pkg/systemstatsmonitor/types/config.go
  pkg/systemstatsmonitor/types/config_test.go
  pkg/util/metrics/system/cmdline_args.go
  pkg/util/metrics/system/cmdline_args_test.go
  pkg/util/metrics/system/module_stats.go
  pkg/util/metrics/system/module_stats_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test

#638 Add vteratipally as an approver
  OWNERS
Labels: lgtm, cncf-cla: yes, size/XS, approved

#650 FIx deprecated "MAINTAINER" in Dockerfile
  Dockerfile
  pkg/util/nethealth/Dockerfile
  test/kernel_log_generator/Dockerfile
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#653 Grammar help
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#628 Change to using new dependency name for osreleaser
  go.mod
  go.sum
  pkg/util/helpers_linux.go
  vendor/github.com/acobaugh/osrelease/.travis.yml
  vendor/github.com/acobaugh/osrelease/LICENSE
  vendor/github.com/acobaugh/osrelease/README.md
  vendor/github.com/acobaugh/osrelease/osrelease.go
  vendor/modules.txt
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#616 Install systemd in docker image
  Dockerfile
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test
