Repository kubernetes/node-problem-detector, pull requests merged in 2023-05, with the labels that each got.

#748 Split proc default and validation between Linux and Windows
  pkg/systemstatsmonitor/types/config.go
  pkg/systemstatsmonitor/types/config_linux.go
  pkg/systemstatsmonitor/types/config_windows.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#749 Add mmiranda96 as a reviewer
  OWNERS
Labels: lgtm, cncf-cla: yes, size/XS, approved

#750 Update README.md
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#746 Update Docker image to Go 1.20.3
  Dockerfile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#755 [fix] cannot patch resource "nodes/status" in API group
  README.md
  deployment/node-problem-detector.yaml
  deployment/rbac.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#745 updated the custom plugin configuration doc
  docs/custom_plugin_monitor.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#756 Remove heapster from project dependencies
  go.mod
  go.sum
  pkg/exporters/k8sexporter/problemclient/configs.go
  pkg/exporters/k8sexporter/problemclient/problem_client.go
  vendor/k8s.io/heapster/LICENSE
  vendor/modules.txt
Labels: lgtm, cncf-cla: yes, size/L, approved
