Repository kubernetes/node-problem-detector, pull requests merged in 2023-09, with the labels that each got.

#808 Update `net_collector_test.go` formatting
  pkg/systemstatsmonitor/net_collector_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#801 Update docker build and fix ARM64 image
  Dockerfile
  Makefile
Labels: lgtm, cncf-cla: yes, size/S, approved

#812 Increase vCPU for Cloud Build
  cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#807 Update tests to run also on macOS
  pkg/healthchecker/health_checker_darwin.go
  pkg/healthchecker/types/types_unix.go
  pkg/systemlogmonitor/logwatchers/filelog/log_watcher_darwin.go
  pkg/systemlogmonitor/logwatchers/kmsg/log_watcher_darwin.go
  pkg/systemstatsmonitor/cpu_collector_unix.go
  pkg/systemstatsmonitor/memory_collector_unix.go
  pkg/systemstatsmonitor/types/config_darwin.go
  pkg/util/exec_unix.go
  pkg/util/helpers_darwin.go
  third_party/forked/cadvisor/tail/tail_linux.go
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test

#813 Remove `GO111MODULE=on` and `-mod vendor` from Makefile
  .travis.yml
  Makefile
  README.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#814 Update Go to v1.21.1
  Dockerfile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#818 Update github.com/coreos/go-systemd to v22.5.0
  go.mod
  go.sum
  pkg/systemlogmonitor/logwatchers/journald/log_watcher.go
  pkg/systemlogmonitor/logwatchers/journald/log_watcher_test.go
  vendor/github.com/coreos/go-systemd/v22/LICENSE
  vendor/github.com/coreos/go-systemd/v22/NOTICE
  vendor/github.com/coreos/go-systemd/v22/internal/dlopen/dlopen.go
  vendor/github.com/coreos/go-systemd/v22/internal/dlopen/dlopen_example.go
  vendor/github.com/coreos/go-systemd/v22/sdjournal/functions.go
  vendor/github.com/coreos/go-systemd/v22/sdjournal/journal.go
  vendor/github.com/coreos/go-systemd/v22/sdjournal/read.go
  vendor/modules.txt
Labels: lgtm, cncf-cla: yes, size/L, approved

#820 Add retry for patch node requests and replace deprecated poll function
  pkg/exporters/k8sexporter/k8s_exporter.go
  pkg/exporters/k8sexporter/problemclient/problem_client.go
  vendor/k8s.io/client-go/util/retry/OWNERS
  vendor/k8s.io/client-go/util/retry/util.go
  vendor/modules.txt
Labels: lgtm, cncf-cla: yes, size/L, approved

#823 Update github.com/avast/retry-go to v4.5.0
  go.mod
  go.sum
  pkg/exporters/stackdriver/stackdriver_exporter.go
  test/e2e/lib/npd/npd.go
  test/go.mod
  test/go.sum
  vendor/github.com/avast/retry-go/.travis.yml
  vendor/github.com/avast/retry-go/Gopkg.toml
  vendor/github.com/avast/retry-go/VERSION
  vendor/github.com/avast/retry-go/appveyor.yml
  vendor/github.com/avast/retry-go/retry.go
  vendor/github.com/avast/retry-go/v4/.gitignore
  vendor/github.com/avast/retry-go/v4/.godocdown.tmpl
  vendor/github.com/avast/retry-go/v4/LICENSE
  vendor/github.com/avast/retry-go/v4/Makefile
  vendor/github.com/avast/retry-go/v4/README.md
  vendor/github.com/avast/retry-go/v4/VERSION
  vendor/github.com/avast/retry-go/v4/options.go
  vendor/github.com/avast/retry-go/v4/retry.go
  vendor/modules.txt
Labels: lgtm, cncf-cla: yes, size/XL, approved
