Repository kubernetes/node-problem-detector, pull requests merged in 2023-12, with the labels that each got.

#828 fix: fix pprof by using DefaultServeMux
  pkg/exporters/k8sexporter/k8s_exporter.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#830 Add hakman as a reviewer
  OWNERS
Labels: lgtm, cncf-cla: yes, size/XS, approved

#825 Add disk and memory percent_used
  config/system-stats-monitor.json
  config/windows-system-stats-monitor.json
  pkg/exporters/stackdriver/stackdriver_exporter.go
  pkg/systemstatsmonitor/disk_collector.go
  pkg/systemstatsmonitor/memory_collector.go
  pkg/systemstatsmonitor/memory_collector_unix.go
  pkg/systemstatsmonitor/memory_collector_windows.go
  pkg/util/metrics/metric.go
  test/e2e/metriconly/metrics_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test
