Repository kubernetes/node-problem-detector, pull requests merged in 2023-02, with the labels that each got.

#716 remove "Start watching journald" to avoid plugin log spam
  pkg/systemlogmonitor/logwatchers/journald/log_watcher.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#717 health-checker cri: fix invalid command
  pkg/healthchecker/health_checker.go
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#735 remove redundant go-get instructions from readme
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#739 update golang to 1.20
  Dockerfile
  go.mod
  go.sum
  vendor/contrib.go.opencensus.io/exporter/prometheus/go.mod
  vendor/contrib.go.opencensus.io/exporter/prometheus/go.sum
  vendor/contrib.go.opencensus.io/exporter/stackdriver/go.mod
  vendor/contrib.go.opencensus.io/exporter/stackdriver/go.sum
  vendor/github.com/fsnotify/fsnotify/go.mod
  vendor/github.com/fsnotify/fsnotify/go.sum
  vendor/github.com/go-ole/go-ole/go.mod
  vendor/github.com/go-task/slim-sprig/go.mod
  vendor/github.com/go-task/slim-sprig/go.sum
  vendor/github.com/google/gofuzz/go.mod
  vendor/github.com/google/uuid/go.mod
  vendor/github.com/googleapis/gax-go/v2/go.mod
  vendor/github.com/googleapis/gax-go/v2/go.sum
  vendor/github.com/json-iterator/go/go.mod
  vendor/github.com/json-iterator/go/go.sum
  vendor/github.com/konsorten/go-windows-terminal-sequences/go.mod
  vendor/github.com/nxadm/tail/go.mod
  vendor/github.com/nxadm/tail/go.sum
  vendor/github.com/onsi/ginkgo/go.mod
  vendor/github.com/onsi/ginkgo/go.sum
  vendor/github.com/onsi/gomega/go.mod
  vendor/github.com/onsi/gomega/go.sum
  vendor/github.com/pborman/uuid/go.mod
  vendor/github.com/pborman/uuid/go.sum
  vendor/github.com/prometheus/procfs/go.mod
  vendor/github.com/prometheus/procfs/go.sum
  vendor/github.com/sirupsen/logrus/go.mod
  vendor/github.com/sirupsen/logrus/go.sum
  vendor/github.com/spf13/pflag/go.mod
  vendor/github.com/spf13/pflag/go.sum
  vendor/go.opencensus.io/go.mod
  vendor/go.opencensus.io/go.sum
  vendor/golang.org/x/oauth2/go.mod
  vendor/golang.org/x/oauth2/go.sum
  vendor/golang.org/x/xerrors/go.mod
  vendor/google.golang.org/appengine/go.mod
  vendor/google.golang.org/appengine/go.sum
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v3/go.mod
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/modules.txt
Labels: lgtm, cncf-cla: yes, size/XL, approved

#743 Update Debian image
  Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test
