Repository kubernetes/node-problem-detector, pull requests merged in 2023-08, with the labels that each got.

#781 Update gcb-docker-gcloud image version
  cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#776 Update README.md: Fix Broken Link to Kubernetes DaemonSet
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#780 Fix missing build arg in `build-in-docker` make target
  Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#773 Replace boskos client with the one in sigs.k8s.io/boskos
  go.mod
  go.sum
  test/e2e/metriconly/e2e_npd_test.go
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/github.com/hashicorp/errwrap/README.md
  vendor/github.com/hashicorp/go-multierror/format.go
  vendor/github.com/hashicorp/go-multierror/sort.go
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/merge.go
  vendor/k8s.io/test-infra/prow/config/secret/BUILD.bazel
  vendor/k8s.io/test-infra/prow/config/secret/agent.go
  vendor/k8s.io/test-infra/prow/config/secret/secret.go
  vendor/k8s.io/test-infra/prow/logrusutil/BUILD.bazel
  vendor/k8s.io/test-infra/prow/logrusutil/logrusutil.go
  vendor/k8s.io/test-infra/prow/version/BUILD.bazel
  vendor/k8s.io/test-infra/prow/version/doc.go
  vendor/k8s.io/utils/inotify/inotify.go
  vendor/k8s.io/utils/inotify/inotify_linux.go
  vendor/k8s.io/utils/inotify/inotify_others.go
  vendor/modules.txt
  vendor/sigs.k8s.io/boskos/LICENSE
  vendor/sigs.k8s.io/boskos/client/BUILD.bazel
  vendor/sigs.k8s.io/boskos/client/README.md
  vendor/sigs.k8s.io/boskos/client/client.go
  vendor/sigs.k8s.io/boskos/common/BUILD.bazel
  vendor/sigs.k8s.io/boskos/common/common.go
  vendor/sigs.k8s.io/boskos/common/config.go
  vendor/sigs.k8s.io/boskos/common/mason_config.go
  vendor/sigs.k8s.io/boskos/storage/BUILD.bazel
  vendor/sigs.k8s.io/boskos/storage/storage.go
  vendor/sigs.k8s.io/yaml/.travis.yml
  vendor/sigs.k8s.io/yaml/OWNERS
  vendor/sigs.k8s.io/yaml/README.md
  vendor/sigs.k8s.io/yaml/yaml.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#774 Add context to long running operations
  cmd/nodeproblemdetector/node_problem_detector.go
  cmd/nodeproblemdetector/node_problem_detector_linux.go
  cmd/nodeproblemdetector/node_problem_detector_test.go
  cmd/nodeproblemdetector/node_problem_detector_windows.go
  cmd/nodeproblemdetector/node_problem_detector_windows_test.go
  pkg/exporters/k8sexporter/condition/manager.go
  pkg/exporters/k8sexporter/condition/manager_test.go
  pkg/exporters/k8sexporter/k8s_exporter.go
  pkg/exporters/k8sexporter/problemclient/fake_problem_client.go
  pkg/exporters/k8sexporter/problemclient/problem_client.go
  pkg/problemdetector/problem_detector.go
  pkg/problemdetector/problem_detector_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#792 Improve docs for health checker and system stats configs
  README.md
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#794 fixed broken links on node-problem-detector
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#788 update k8s.io to latest 0.17 patch version for fix to CVE-2020-8564
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/helpers.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/k8s.io/client-go/transport/round_trippers.go
  vendor/k8s.io/client-go/util/connrotation/connrotation.go
  vendor/modules.txt
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test

#796 Add sig-node approvers and reviewers to OWNERS/OWNERS_ALIASES
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, cncf-cla: yes, size/S, approved
