Repository kubernetes/node-problem-detector, pull requests merged in 2024-03, with the labels that each got.

#876 Update Go to v1.22.1
  Dockerfile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#880 Remove push-tar
  Makefile
Labels: lgtm, cncf-cla: yes, size/S, approved

#879 Bump NPD versions to v0.8.17
  deployment/node-problem-detector-healthchecker.yaml
  deployment/node-problem-detector.yaml
  pkg/systemstatsmonitor/memory_collector_unix.go
  test/go.mod
  test/go.sum
Labels: lgtm, cncf-cla: yes, size/S, approved

#873 Update release process
  docs/release_process.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#882 Revert "Remove push-tar"
  Makefile
Labels: lgtm, cncf-cla: yes, size/S, approved

#883 Add make release
  Makefile
  docs/release_process.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#886 Declare 'builder' image in two steps to allow overriding the value
  Dockerfile
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#888 Update dependencies every week
  .github/workflows/update-deps.yml
Labels: lgtm, cncf-cla: yes, size/M, approved

#856 fix bug in skip_initial_status
  pkg/custompluginmonitor/custom_plugin_monitor.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#864 Get Node object from APIServer cache
  pkg/exporters/k8sexporter/problemclient/problem_client.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#891 Update BASEIMAGE to debian-base:bookworm-v1.0.2
  Dockerfile
  Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved
