Repository kubernetes/node-problem-detector, pull requests merged in 2024-04, with the labels that each got.

#890 Add support for CBL-Mariner and Azure Linux
  pkg/util/helpers_linux.go
  pkg/util/helpers_linux_test.go
  pkg/util/testdata/os-release-azurelinux
  pkg/util/testdata/os-release-mariner
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#894 Update Go to v1.22.2
  Dockerfile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#896 Add MachineHealthChecks of Cluster API
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#897 Bump NPD versions to v0.8.18
  deployment/node-problem-detector-healthchecker.yaml
  deployment/node-problem-detector.yaml
  test/go.mod
  version.txt
Labels: lgtm, cncf-cla: yes, size/XS, approved

#900 Explain compatibility in README
  README.md
Labels: lgtm, cncf-cla: yes, size/S, approved
