Repository kubernetes/node-problem-detector, pull requests merged in 2024-10, with the labels that each got.

#965 Update golang to 1.23.1 in go.mod
  go.mod
  test/go.mod
Labels: lgtm, cncf-cla: yes, size/XS, approved

#966 chore: Dependabot config cleanup
  .github/dependabot.yml
Labels: lgtm, cncf-cla: yes, size/M, approved

#974 Skip ext4 e2e tests
  test/e2e/metriconly/metrics_test.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#972 Update cloud.google.com/go/compute/metadata to v0.5.2
  go.mod
  go.sum
  test/go.mod
  test/go.sum
  vendor/cloud.google.com/go/compute/metadata/CHANGES.md
  vendor/cloud.google.com/go/compute/metadata/metadata.go
  vendor/cloud.google.com/go/compute/metadata/retry_linux.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_noinit.go
  vendor/golang.org/x/sys/cpu/cpu_linux_riscv64.go
  vendor/golang.org/x/sys/cpu/cpu_riscv64.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_hurd.go
  vendor/golang.org/x/sys/unix/zerrors_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_zos_s390x.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_386.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_arm.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: lgtm, cncf-cla: yes, size/L, approved

#955 Move ReadonlyFilesystem Node Condition to a new configuration file
  Dockerfile
  config/kernel-monitor.json
  config/readonly-monitor.json
  config/systemd/node-problem-detector-metric-only.service
  deployment/node-problem-detector-config.yaml
  deployment/node-problem-detector-healthchecker.yaml
  deployment/node-problem-detector.yaml
  test/build.sh
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#961 add black list to aviod take too much efforts to translate in file log watcher
  config/disk-log-message-filelog.json
  pkg/systemlogmonitor/logwatchers/filelog/log_watcher.go
  pkg/systemlogmonitor/logwatchers/filelog/log_watcher_test.go
  pkg/systemlogmonitor/logwatchers/types/log_watcher.go
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#976 Update version to v0.8.20
  version.txt
Labels: lgtm, cncf-cla: yes, size/XS, approved

#980 feature: add QPS Burst flags for client cfg
  cmd/options/options.go
  pkg/exporters/k8sexporter/problemclient/problem_client.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/feature
