Repository kubernetes/node-problem-detector, pull requests merged in 2024-09, with the labels that each got.

#944 Update update-deps.yml
  .github/workflows/update-deps.yml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#912 [StepSecurity] Apply security best practices
  .github/dependabot.yml
  .github/workflows/codeql.yml
  .github/workflows/dependency-review.yml
  .github/workflows/scorecards.yml
  .github/workflows/tag-release.yml
  .github/workflows/update-deps.yml
  .pre-commit-config.yaml
  Dockerfile
  Makefile
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test

#956 chore: Remove broken workflow update-deps.yml
  .github/workflows/update-deps.yml
Labels: lgtm, cncf-cla: yes, size/L, approved
