Repository kubernetes/node-problem-detector, pull requests merged in 2024-08, with the labels that each got.

#915 chore: Remove unused binary `nethealth`
  pkg/util/nethealth/Dockerfile
  pkg/util/nethealth/Makefile
  pkg/util/nethealth/README.md
  pkg/util/nethealth/nethealth.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#938 Update update-deps.yml with dockerfile update
  .github/workflows/update-deps.yml
Labels: lgtm, cncf-cla: yes, size/M, approved

#940 Update abrt-adaptor.json
  config/abrt-adaptor.json
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#942 Update update-deps.yml update-go-version job
  .github/workflows/update-deps.yml
Labels: lgtm, cncf-cla: yes, size/S, approved
