Repository kubernetes/node-problem-detector, pull requests merged in 2024-01, with the labels that each got.

#819 Tag releases via PR
  .github/workflows/tag-release.yml
  hack/tag-release.sh
  version.txt
Labels: lgtm, cncf-cla: yes, size/M, approved

#849 Make pattern match all systemd StatusUnitFormat
  config/systemd-monitor-counter.json
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#848 Support revert-pattern in logcounter
  cmd/logcounter/options/options.go
  config/systemd-monitor-counter.json
  pkg/logcounter/log_counter.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#852 Update config/systemd-monitor.json to match all systemd StatusUnitFormat
  config/systemd-monitor.json
Labels: lgtm, cncf-cla: yes, size/XS, approved

#853 Bump google.golang.org/grpc to v1.57.1
  go.mod
  go.sum
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: lgtm, cncf-cla: yes, size/M, approved
