Repository kubernetes/node-problem-detector, pull requests merged in 2024-05, with the labels that each got.

#908 Update Go to v1.22.3
  .github/workflows/update-deps.yml
  Dockerfile
  Makefile
  go.mod
  test/go.mod
Labels: lgtm, cncf-cla: yes, size/S, approved

#909 Add rocky linux support to GetOSVersion
  pkg/util/helpers_linux.go
  pkg/util/helpers_linux_test.go
  pkg/util/testdata/os-release-rocky
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#913 Add helper script to print sha/md5 of tar files
  Makefile
  hack/print-tar-sha-md5.sh
Labels: lgtm, cncf-cla: yes, size/M, approved

#914 Bump NPD versions to v0.8.19
  deployment/node-problem-detector-healthchecker.yaml
  deployment/node-problem-detector.yaml
  docs/release_process.md
  test/go.mod
  version.txt
Labels: lgtm, cncf-cla: yes, size/S, approved
