Repository kubernetes/node-problem-detector, pull requests merged in 2025-03, with the labels that each got.

#845 Monitor XFS shutdown
  config/kernel-monitor.json
Labels: lgtm, cncf-cla: yes, size/S, approved, lifecycle/stale, ok-to-test

#1024 Move disk and memory metrics in custom group to compute
  pkg/exporters/stackdriver/stackdriver_exporter.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1021 feat(k8sExporter): Options to allow disabling Events or Node Conditions
  cmd/options/options.go
  pkg/exporters/k8sexporter/k8s_exporter.go
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#1037 Removed draino from README
  README.md
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test
