Repository kubernetes/node-problem-detector, pull requests merged in 2025-08, with the labels that each got.

#1094 Fix test instance name
  test/e2e/metriconly/metrics_test.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1098 fix dockerfile warnings
  Dockerfile
Labels: lgtm, cncf-cla: yes, size/S, approved

#1092 feat: Add support for Flatcar Container Linux
  pkg/util/helpers_linux.go
  pkg/util/helpers_linux_test.go
  pkg/util/testdata/os-release-flatcar
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#1099 Update Go to v1.24.6
  Dockerfile
  go.mod
  test/go.mod
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1087 docs: Add versioning proposal
  docs/versioning.md
Labels: lgtm, cncf-cla: yes, size/M, approved
